### ISSUE TITLE
MiniWallet - Launch Task List

### ISSUE THREAD

**Issue by johnwhitton** [polymorpher/sms-wallet#13]
This issue can be used to track the tasks for MiniWallet and MiniServer as we prepare for Go Live.
Also we can provide a log of activity.

## Work Streams
Currently there are a number of work streams which can be consolidated and merged.
- https://github.com/polymorpher/sms-wallet/issues/5
- https://github.com/polymorpher/sms-wallet/issues/3 
- https://github.com/polymorpher/sms-wallet/issues/10

## Open PR's
- #11 
  -  Suggest we merge this as it contains all changes
- Alternately could merge the tickets as follows
  - #8 
  - #12 
  - #11 

## Completed
Have closed the following PR's as they have been superseded
- #6 (worked on under 7)
- #7 (worked on under 8)
- #9 (replaced by 12)

And the following have been closed as they are now being progressed here
- #7 
- #8 
- #10 
- #11 
- #12 

## To Do
- [ ] [Build NFTId Functionality](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/NFTID.md)  
- [ ] [Proxy Deployment Improvements](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/PROXY.md#improvements)
- [ ] [Demo and Docs for MiniWallet Server](https://github.com/polymorpher/sms-wallet/issues/5)
- [ ] [MiniWallet Enhancements](https://github.com/polymorpher/sms-wallet/issues/3)

**Comment by johnwhitton** [comment]
**Work Log**
**August 29th**
MiniServer: include operator functionality to allow multiple operators to sign transactions per server

**August 30th**
MiniWallet: Refactor from AssetManager to MiniWallet and enhance approve functionality to allow depositing of funds simultaneously

**Aug 31st**
I configured datastore to run locally
Added an additional Creator wallet to twilio and registered it
Updated the authorization requests to be from the creator (previously they were just approving from the user to itself)
I got upgrades working using hardhat-deploy
You can have a look here
https://github.com/polymorpher/sms-wallet/pull/9

**Sep 1st**
Created NFT Scaffolding
Consolidated PR's

**Other Items**
**MiniWallet Demo Page:** I think it makes sense to add another page to Demo and include the ability to generate the authorization requests 
**Mini Wallet Demo Page Optional:** perhaps some read only functions for MiniWallet (e.g. user getting balances or listing all your approvals and creators listing all the approvals that exist for them)
**Creator Guide:** Document the flow from registering as a creator, asking for funds (can do this as a markdown page in the wiki (or docusaurus) or add it into Demo
**Transfer:** Still need to build out an API for transfer of non-native tokens
**Other Items:** Listed in Optional Enhancements https://github.com/polymorpher/sms-wallet/issues/5
**Go Live Tasks:** Listed Here https://github.com/polymorpher/sms-wallet/issues/3

**Comment by johnwhitton** [comment]
Have Pushed Latest Changes under #14 
Merged Latest Master with the NFT changes from #15 
Worked through feedback on  #7 and #8 and closed those PR's 
Currently working through feedback on https://github.com/polymorpher/sms-wallet/pull/11
Next
Retest with NFT changes from #15
Finish up NFT Identity
Work on MiniWallet Demo
Work on [Proxy Improvements](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/PROXY.md#improvements)

@polymorpher can you help clarify this feedback item
https://github.com/polymorpher/sms-wallet/pull/8#discussion_r962375862

**Current Coverage Report**
```
-------------------------------------------------|----------|----------|----------|----------|----------------|
File                                             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------------------|----------|----------|----------|----------|----------------|
 contracts/                                      |      100 |       70 |      100 |    92.31 |                |
  Enums.sol                                      |      100 |      100 |      100 |      100 |                |
  MiniWallet.sol                                 |      100 |       70 |      100 |    92.31 |... 517,567,604 |
  MiniWallet_v2.sol                              |      100 |      100 |      100 |      100 |                |
 contracts/debug/                                |    26.32 |        0 |    13.64 |    24.39 |                |
  TestTokens.sol                                 |    26.32 |        0 |    13.64 |    24.39 |... 154,158,166 |
 contracts/lib/                                  |       25 |     12.5 |       25 |       25 |                |
  SafeCast.sol                                   |       25 |     12.5 |       25 |       25 |7,8,12,13,17,18 |
 contracts/nft/                                  |    88.61 |       75 |    87.88 |       89 |                |
  Mini1155.sol                                   |    92.31 |    68.75 |    94.12 |    92.52 |... 407,408,413 |
  Mini721.sol                                    |    84.69 |    81.82 |    81.25 |    85.29 |... 361,362,367 |
 contracts/nft/ERC721M/                          |    88.98 |    59.38 |    83.87 |    87.05 |                |
  ERC721M.sol                                    |    88.98 |    59.38 |    83.87 |    87.05 |... 634,635,637 |
 contracts/nft/ERC721M/extensions/               |        0 |        0 |        0 |        0 |                |
  ERC721MBurnable.sol                            |        0 |        0 |        0 |        0 |    24,26,30,32 |
  ERC721MOwnersExplicit.sol                      |        0 |        0 |        0 |        0 |... 41,42,43,47 |
 contracts/nft/rarible/royalties/contracts/      |        0 |      100 |        0 |        0 |                |
  IRoyaltiesProvider.sol                         |      100 |      100 |      100 |      100 |                |
  LibPart.sol                                    |        0 |      100 |        0 |        0 |             14 |
  LibRoyaltiesV2.sol                             |      100 |      100 |      100 |      100 |                |
  RoyaltiesV2.sol                                |      100 |      100 |      100 |      100 |                |
 contracts/nft/rarible/royalties/contracts/impl/ |    63.64 |    33.33 |       75 |    63.64 |                |
  AbstractRoyalties.sol                          |    55.56 |    33.33 |       50 |    55.56 |    20,21,22,23 |
  RoyaltiesV2Impl.sol                            |      100 |      100 |      100 |      100 |                |
-------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                        |     80.3 |    58.47 |    73.47 |    78.66 |                |
-------------------------------------------------|----------|----------|----------|----------|----------------|

```

**Comment by johnwhitton** [comment]
Initial test of NFT Functionality gave the following
![Screenshot 2022-09-04 at 8 01 34 PM](https://user-images.githubusercontent.com/1572027/188352742-2eb09755-67a5-4847-861c-369ff32e94e2.png)

Looks like we need to have DUMMY NFT's created in local environment.
https://github.com/polymorpher/sms-wallet/blob/main/client/src/pages/NFT.jsx#L295
```
const DUMMY_NFTS = [{
  contractAddress: '0x426dD435EE83dEdb5af8eDa2729a9064C415777B',
  tokenId: '1',
  tokenType: 'ERC721',
}, {
  contractAddress: '0x426dD435EE83dEdb5af8eDa2729a9064C415777B',
  tokenId: '2',
  tokenType: 'ERC721',
}, {
  contractAddress: '0x6b2d0691dfF5eb5Baa039b9aD9597B9169cA44d0',
  tokenId: '1',
  tokenType: 'ERC1155',
}, {
  contractAddress: '0x6b2d0691dfF5eb5Baa039b9aD9597B9169cA44d0',
  tokenId: '2',
  tokenType: 'ERC1155',
}]
```

**Comment by johnwhitton** [comment]
Closed PR #11 will progress under PR #14 
Action items from #11 
- [ ] Multi-call MintForCommunity
- [ ] Deployment Scripts
- [ ] Update NFT UI to use deployed contracts as DUMMY_TOKENS
- [ ] Registration WorkFlow

**Comment by johnwhitton** [comment]
**Status Update**
1. Yesterday progressed Deployments and Proxy (working with @wighawag to troubleshoot hardhat-deploy OpenZepplin UUPS compatibility [see here](https://github.com/wighawag/hardhat-deploy/issues/146), [commit](https://github.com/polymorpher/sms-wallet/pull/14/commits/c96998273c1d258ac0c150eaac7a1ae182da8f57), [writeup](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/PROXY.md#improve-transparency-and-readabilty)
2. Today I put some initial scaffolding in for MiniID Minting and Lookup [see here](https://github.com/polymorpher/sms-wallet/pull/14/commits/80c707c372829ba7600597dac5790aa8aa2d7072)

**Next Steps (this week)**
1. Mini721 and Mini1155 Deploys
2. Update DummyNFT Config to use .env and test locally
3. Manually create sample metadata and mint tokens for all 3 contracts (MiniID,Mini721,Mini1155)
4. Validate they show in the sms-wallet UI
5. Test the Lookup API
6. Code the Mint API [see here](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniserver/routes/miniID.js#L23)

**Additional Cleanup**
1. I'd like to consistently use ethers rather than web3, should be able to consolidate code codebase to use ethers in a couple of hours.

**Comment by johnwhitton** [comment]
**Status Update**

1. Updated the [Approach and Design for NFT's](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/NFTID.md)
2. Deployed [3 tokens MiniID, Mini721 and Mini1155](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/NFTID.md#tokens) and tested integration with client UI

**Next Steps**
The steps above are still accurate

**Detailed Items/Issues**
1. Images are not showing on the UI unless hardcoding the url [see here](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/NFTID.md) @polymorpher help appreciated
2. Need feedback from @polymorpher on the approach and priority of the Mini contracts
3. Have to update metadata and deployment scripts as follows
    1. ALL - need to redeploy metadata files without the .json suffix
    2. Mini721 - need to update the baseURI (similar to miniID)
    4. Mini1155 - need to deploy metadata [Following these guidelines](https://eips.ethereum.org/EIPS/eip-1155#metadata)

**Comment by johnwhitton** [comment]
**My next steps are**
1. Get the scaffolding in place for generating the QR codes using vcard as a starting point https://blog.beaconstac.com/2019/12/vcard-qr-code-design/
2. Work on the miniwallet NFT token approval and transfer functionality
3. Modify/enhance the contracts to deliver functionality we discussed (MiniID, Mini721 and Mini1155(includes operator functionality for minting and issuing tokens)
4. Troubleshoot NFT UI issues
5. Create the MiniWallet Demo Pages and Documentation

**Comment by johnwhitton** [comment]
**Notes on testing NFT client functionality**
1. DUMMY_NFTs sets the contract and tokenId to display as a default for all users. If the user does not own that token it does not display it. In our case (3 contracts each user owning different tokenID’s) it is better to ignore DUMMY_NFT’s and add the NFT’s manually.
2. When adding an NFT you need to refresh the screen before it displays
3. Sometimes retrieving tokenId metadata and images from ipfs fails with a 504. Refreshing multiple times usually fixes it.
4. When Hiding an NFT get this error `Failed to hide token. Error: TypeError: Cannot read properties of undefined (reading 'find')`. Doing a refresh shows the hidden token removed.
5. When adding an NFT there is no cancel button. So if you can't add an NFT e.g. because you don't own it. The only way to remove the dialogue is to refresh the screen.


**Notes on Test Data**
For our user (+14158401410 address 0x864966c7483155C090BB07AB3Fb130c159c18daf) we have issued the following Tokens
1. MiniID: There Soulbound Identity
2. Mini721: A collectible issued to them (Minion Image)
3. Mini1155: A friends or fans token issued from the operator
4. Mini1155: A friends or fans token issued by the creator

The sms-wallet UI looks as follows (on a phone it shows the first image and then you can scroll up and down)
![Screenshot 2022-09-10 at 11 51 05 AM](https://user-images.githubusercontent.com/1572027/189497841-7b218e3f-8286-4dcb-854e-7f19ba52722e.png)

For our creator (+16505473175 address 0x7A78C8A0F61a9015440ac970D390f596836C9872) we have issued the following Tokens
1. MiniID: There Soulbound Identity
2. Mini721: A collectible issued to them (Minion Image)
3. Mini1155: A friends or fans token issued from the operator
<img width="337" alt="Screenshot 2022-09-10 at 12 04 45 PM" src="https://user-images.githubusercontent.com/1572027/189498200-571c7baf-6488-40b2-b477-6cc5475833d1.png">

**Comment by johnwhitton** [comment]
Just pushed an initial commit for the miniID APIs [here](https://github.com/polymorpher/sms-wallet/pull/14/commits/8b60043c6fd3cf36310ad90f723979d648603bf5)

Below are some overlap between miniserver and server and some discussion points for API design consolidation
* If using [mock datastore](https://github.com/polymorpher/sms-wallet/blob/main/server/src/data/datastore.js#L10) in both server and MiniServer then both will try and start the mock datastore and the second will fail. Also if starting the miniserver first, shutting down the server does not stop the mock datastore. 
* blockchain.js currently have one in server and one in miniserver want to leverage the generic apis such as `await apis.blockchain.getTokenBalance` which exists in server on miniserver. 
  * Potentially rename minserver blockchain.js to operator.js and only include the operator functions all other read functions can be moved into servers blockchain.js
* middleware.js currently have one in server and one in miniserver. 
  * Potentially moving all middleware functionality (except for operator to server => middleware and call this from miniserver (any operator specific middleware can go into the miniserver in a file named opmiddleware.js (or something similar).

**Comment by johnwhitton** [comment]
**Status Update**
* Have implemented our own proxy and tested upgrade process [details can be found here](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/devlog/PROXY.md#improve-transparency-and-readabilty)
* Working through feedback on https://github.com/polymorpher/sms-wallet/pull/14 and applying changes to the MiniV0 branch
* Next is breaking down the PR's as defined [here](https://github.com/polymorpher/sms-wallet/pull/14#issuecomment-1243443278)

**Let's break down this PR into multiple parts (each has its own PR):**

1. core mini-wallet (server, contract, tests) - these are ready for merge
2. mini-wallet deployment and upgrade scripts - these needs some improvement on fine-control over deploy and upgrade process (most likely can't just use simple hardhat calls / plugins anymore) and storing (not just logging) the addresses of proxy, logic, and storage `On a second thought - I think (2) can be merged in after using a better proxy, so we can get it up and running ASAP. We can improve this process in a later PR`
3. mini1155, 721, and related deployment scripts and tests - these need some sanitization and maybe some simplification on tests. They are pretty much ready for merge
4. miniID related and other WIP stuff - these are incomplete
5. documentations (NFTID.md, PROXY.md) - these need further review and some revision - I can also edit on the branch itself
The PRs can be made in chains (each PR's branch merge into the branch of previous PR) rather than all pointing to the base (main) branch, since each may be dependent on some of the work in previous PR

**Comment by johnwhitton** [comment]
**Status Update**
* Refactored MiniWallet work streams see [commit here](https://github.com/polymorpher/sms-wallet/commit/f8519910a324b20e93ac631cea98e39eddee87c1) and [approach here](https://github.com/polymorpher/sms-wallet/blob/miniV0/miniwallet/devlog/CONFIGURATION.md)

**Next Steps (Tomorrow)**
* Address all the Feedback in https://github.com/polymorpher/sms-wallet/pull/14
* Create PR's for 1 and 2 above

**Comment by johnwhitton** [comment]
Workstreams are being broken down and documented in [FEATURE_ROLLOUT.md](https://github.com/polymorpher/sms-wallet/blob/ws-miniwallet-v0/miniwallet/devlog/FEATURE_ROLLOUT.md)
First feature to be deployed is miniWallet (contract and miniserver) write up is [here](https://github.com/polymorpher/sms-wallet/blob/ws-miniwallet-v0/miniwallet/devlog/FEATURE_ROLLOUT.md#core-mini-wallet-server-contract-tests) and Pull Request is [here](https://github.com/polymorpher/sms-wallet/pull/16)
**Note all commits up to [7f3c01b](https://github.com/polymorpher/sms-wallet/pull/16/commits/7f3c01bef26b9ba484ed47d1cc4704425d95443b) have been reviewed under [miniV0](https://github.com/polymorpher/sms-wallet/pull/14)**

@polymorpher let me know if it's easier for review purposes for me to rebase miniV0.

🙏 💙 🙏
