### ISSUE TITLE
MiniWallet Smart Contracts Testing and Deployment

### ISSUE THREAD

**Issue by johnwhitton** [polymorpher/sms-wallet#3]
This Issue tracks the next steps for the SMS-Wallet Smart Contracts (Chaincode) 
It follows on from Pull Request https://github.com/polymorpher/sms-wallet/pull/1 enhancing and hardening testing, deployment and adding in additional ERC777 functionality

### ToDo

**Priority Tasks**
- [x] **Rename AssetManager.sol to MiniWallet.sol**
- [x] **Add deposit functionality to approve** 
- [ ] Change all requires to if tests and error messages
- [ ] Testing
   - [ ] Additional tests for `require`, `modifiers` and `pausable` functions
   - [ ] Additional tests when adding operators over thresholds
   - [ ] Additional tests for depositing or approving funds over global limits
   - [ ] [Refactor testing](https://github.com/polymorpher/sms-wallet/pull/1#discussion_r936058784) 
- [x] Deployment
  - [x] Review deployment best practices for proxies including using [hardhat-deploy](https://github.com/wighawag/hardhat-deploy/tree/master) instead of [openzepplin upgrades](https://docs.openzeppelin.com/upgrades-plugins/1.x/)
  - [ ] Deploy to Testnet
  - [ ] Verify contract on Testnet
  - [x] **Test Contract Upgrade Process**
- [ ] Go Live Checklist
  - [ ] Testnet Deploy
  - [ ] Testnet MinServer Integration
  - [ ] Production Deploy  
- [ ] Add [multicall](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol) functionality for batch requests

Additional Tasks 
- [ ] Add in support for ERC777.  References [ERC-777 Sample Code](https://github.com/abcoathup/Simple777Token), [EIP-777](https://eips.ethereum.org/EIPS/eip-777), [OpenZepplin ERC777 Documentation](https://docs.openzeppelin.com/contracts/4.x/erc777), [OpenZepplin ERC777.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC777/ERC777.sol), [OpenZepplin ERC777 Example Implementation](https://forum.openzeppelin.com/t/simple-erc777-token-example/746), [ERC777 Masters Thesis](https://github.com/0xjac/master-thesis/blob/master-pdf/JacquesDafflon-masterthesis.pdf)
  - [ ] Initial code is was done in commit  https://github.com/polymorpher/sms-wallet/commit/b467f85544b89c110c00b7097b7f162df4155355 on branch [jw-erc-777](https://github.com/polymorpher/sms-wallet/tree/jw-erc777)
- [ ] Documentation: add how to run coverage server and 
  - [ ] [Hardhat support for Harmony](https://github.com/KangaFinance/hardhat/commits/master)
 - [ ] Enhancements
   - [ ] Replace all requires with if tests reverts and custom errors
   - [ ] Could introduce warning events when changing thresholds if user has a balance over the new threshold 
 - [ ] Optimizations
   - [ ] Review [contract optimization best practices](https://github.com/polymorpher/sms-wallet/pull/1#issuecomment-1207466614) 
 - [ ] Security 
   - [ ] add `yarn.lock` to gitIgnore [comments here](https://github.com/polymorpher/sms-wallet/pull/1#issuecomment-1207399684)

**Outstanding Issues/Clarifications**
- [ ] ERC721 safeTransferFrom not working in AssetManager.ts (using transferFrom)
- [ ] ERC1155 safeTransferFrom needs "0x" passed for data in AssetManager.ts ("" in AssetManager.sol)
- [ ] Review errorHanding for transfer (currently capture failures for ERC20 but not ERC721 and ERC1155).
- [ ] Deploy failing with [unpredicatable gas limit](https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT) was caused when there was a bug in the contract (not setting the admin role before setting operators) if this happens again may need to apply [this workaround to fix gas price](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/85#issuecomment-1028435049)
